name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  QT_VERSION:   5.15.2

jobs:
  install_packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'linux'
        target: 'desktop'
        arch: gcc_64
        dir: .
        install-deps: 'true'
        modules: qtwebengine
        setup-python: 'false'

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: installed-packages
        path: .

  build:
    needs: [install_packages]
    runs-on: ubuntu-latest

    steps:
    - name: Download packages
      uses: actions/download-artifact@v3
      with:
        name: installed-packages
        path: .
    
    - name: find
      run: |
        ls
        pwd

    - name: Build Project
      run: |
        echo "::set-env name=QTDIR::$(pwd)/Qt/5.15.2/gcc_64"
        echo "::add-path::$(pwd)/Qt/5.15.2/gcc_64/bin"
        echo "::add-path::$(pwd)/Qt/5.15.2/gcc_64/lib"
        chmod +x build.sh
        ./build.sh
      
    - name: Build Tests
      run: |
        chmod +x buildTest.sh
        ./buildTest.sh

  testing:
   needs: [build]
   runs-on: ubuntu-latest

   steps:
   - name: Run Tests
     run: |
       chmod +x runTest.sh
       ./runTest.sh


# export PATH=$PATH:/home/runner/work/_temp/Qt/5.15.2/gcc_64/bin/qmake
