name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        components: 'qtbase qtdeclarative qttools qtlocation qtwebenginewidgets qtnetwork'
    
    - name: PRINT
      run : | 
          ls
          
    - name: Build Project
      run: |
        chmod +x build.sh
        ./build.sh
      
    - name: Build Tests
      run: |
        chmod +x buildTest.sh
        ./buildTest.sh
      
    - name: Run Tests
      run: |
        chmod +x runTest.sh
        ./runTest.sh
